const ExtractTextPlugin = require('extract-text-webpack-plugin');


// The pattern for classnames generated by CSS modules:
const CSS_MODULES_CLASS_PATTERN = '[name]__[local]___[hash:base64:5]';

// Params for css-loader to set up CSS Modules with a specific class pattern
// and add postcss-loader:
const CSS_MODULES_OPTIONS = {
  modules: true,
  localIdentName: CSS_MODULES_CLASS_PATTERN,
  importLoaders: 1,
};

const POSTCSS_OPTIONS = {
  plugins: function() {
    return [
      require('postcss-import'),
    ];
  },
};

const CSS_MODULES_LOADERS = {
  // Used server-only
  // CLASSNAMES_ONLY: [
  //   {
  //     loader: 'css-loader/locals',
  //     options: CSS_MODULES_OPTIONS,
  //   },
  //   'postcss-loader',
  // ],

  // production
  FILE: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      {
        loader: 'css-loader',
        options: CSS_MODULES_OPTIONS,
      },
      {
        loader: 'postcss-loader',
        options: POSTCSS_OPTIONS,
      }
    ],
  }),

};

const config = {
  entry: './src/index.js',
  output: {
    path: `${__dirname}/build`,
    filename: 'index.js',
  },
  resolve: {
    modules: [__dirname, 'node_modules'],
  },

  // CSS Modules.
  module: {
    rules: [
      {
        test: /\.css$/,
        exclude: [/node_modules/, /\.global\.css$/],
        loader: CSS_MODULES_LOADERS.FILE,
      },
    ],
  }
}

module.exports.default = config;
